### ISSUE TITLE
Display manager

### ISSUE THREAD

**Issue by delroth** [prologin/sadm#1]
> ###### Originally posted 2012-01-10 01:16 by [delroth](https://bitbucket.org/delroth/) on Bitbucket

Basically:

* gdm blows
* xdm sucks

We need a good one which can be launched on 100 machines without crashing.

**Comment by delroth** [comment]
> ###### Originally posted 2013-05-16 21:42 by [delroth](https://bitbucket.org/delroth/) on Bitbucket

KDM worked fine this year, but we need to look into customization.

**Comment by audebert** [comment]
> ###### Originally posted 2015-02-08 21:01 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

KDM again for Paris I 2015, worked well. 

Easy customization can be achieved by editing/copying the xml and png of an existing theme. For an example theme, see: https://www.archlinux.org/packages/community/any/archlinux-themes-kdm/

I vote for KDM for the 2015 final.

**Comment by audebert** [comment]
> ###### Originally posted 2015-04-02 12:38 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

Tested LightDM with gtk greeter, not convinced:

- **-** Had to create a bunch of other tmpfs
- **-** Could not get it to display PAM errors from ``pam_presenced.py``.
- **+** Displays keyboard layout switcher
- **+** Display session switcher (there was only MATE desktop while kde desktop was also installed...)
- Configuration files used:

```
#!ini


# /etc/lightdm.conf
[LightDM]
minimum-vt=1
user-authority-in-system-dir=true
run-directory=/run/lightdm

[SeatDefaults]
greeter-hide-users=true
greeter-show-manual-login=true
session-wrapper=/etc/lightdm/Xsession
```

```
#!ini

# /etc/lightdm/lightdm-gtk-greeter.conf
[greeter]
allow-debugging = true
hide-user-image = true
```

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-04-18 21:54 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

What's the outcome of this issue? Keeping KDE Display Manager?

**Comment by audebert** [comment]
> ###### Originally posted 2015-04-20 18:47 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

KDM does not support keyboard layout switching, I will look at SDDM and compare to LightDM.

**Comment by audebert** [comment]
> ###### Originally posted 2015-04-30 18:01 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

During the 30/04 check-sm, we tested SDDM, unfortunately it was crashing as soon as it was started. The only way to get it to work was to do the following:


```
#!shell

$ systemctl start kdm
$ systemctl stop kdm
$ systemctl start sddm
```

SDDM works well on my virtual setup, so it might be an issue with the video driver.

The elarun theme provides the traditional login/password fields, a session selector and a keyboard layout switcher.

**Comment by audebert** [comment]
> ###### Originally posted 2016-04-01 03:59 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

KDM is deprecated and not in the Arch Linux repository anymore. SDDM is the new recommended login manager.

It was used for Paris I 2016 and had keymap selection and login+pasword fields. We did a good looking (ymmv) custom theme painlessly in a less than an hour. The hack to display the error message from pam_presenced did not work and we had to disable it.

**Action item**: Check that the error box is still broken.

If it is, edit `sadm/python-lib/prologin/presenced/pam_presenced.py` and modifiy the `fail()` function so that it displays the error message in a user friendly box under sddm.

Ideas:

1. Check that the XAUTHORITY retrieval hack is not broken with sddm, iirc that was the problem.
2. We should remove this hack and use pam error reporting functions and sddm should be able to display them correctly.
3. We use pam_exec(8) to do our hook, and I am not sure there we can report errors with that thing.
4. If so, rewrite the PAM using python: https://pypi.python.org/pypi/simplepam

**Comment by seirl** [comment]
> ###### Originally posted 2016-05-05 11:08 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

fc372445a68070f905b82314d4d41a726ec2c909 automates the deployment of a custom Prologin theme with login/password fields, session selector and keyboard layout switcher. Some configuration is still needed to add keyboard layouts.

**Comment by seirl** [comment]
> ###### Originally posted 2016-05-08 20:14 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

bc31e94 uses xhack implemented in edcf39c to fix the XAUTHORITY retrieval hack. Still a hacky solution though :(

**Comment by cafehaine** [comment]
Gnome shell now includes wayland, which might not work with sddm given this issue : sddm/sddm#440
(Also KDE seems close to switching to wayland)

**Comment by seirl** [comment]
We've pretty much moved to sddm now. If it breaks because of Wayland, we can open a new issue.
