### ISSUE TITLE
Add multiple packages to IgnorePkg

### ISSUE THREAD

**Issue by seirl** [prologin/sadm#120]
- linux
- postgresql
- ...

**Comment by Marcerisson** [comment]
Also, in `install_scripts/setup_sadm.sh:26`, there is twice `postrgesql-libs`

**Comment by Marcerisson** [comment]
@multun so which of those do we need to prevent from upgrading?

**Comment by multun** [comment]
@Marcerisson I couldn't think of anything else but the list @seirl gave:

 - `linux` because it breaks contestant machines boot (the kernel doesn't match its modules anymore)
 - `postgresql` and `postgresql-libs` as it is the most critical component of sadm ; it would be a shame for an upgrade to break anything

**Comment by seirl** [comment]
`postgresql` is not because it's a critical component, but because upgrades require manual interventions (for the cluster migration to the newer version).

**Comment by multun** [comment]
oh yeah for majors right
