### ISSUE TITLE
Work on UDB and MDB admin panels

### ISSUE THREAD

**Issue by seirl** [prologin/sadm#38]
> ###### Originally posted 2015-02-08 19:03 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

Some bugs/problems encountered during the regionals:

* UDB seemed completely freezed (no way to edit a group or add an user)
* You have to manually specify the uids in UDB and the IP in MDB (no way to get a sane default) 
* The ugly --uid-base in udb/manage.py
* MDB must reject invalid hostnames (eg. containing '_')

**Comment by audebert** [comment]
> ###### Originally posted 2015-03-31 15:06 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

* UDB seemed completely freezed (no way to edit a group or add an user)

Probably because we used a Django super admin that was not in the "root" ``udb`` group. We always have to use users created by ``batchimport`` to access ``udb`` or ``mdb`` admin panels.

* You have to manually specify the uids in UDB and the IP in MDB (no way to get a sane default)
* The ugly --uid-base in udb/manage.py

Created issue #44 for UID, and #45 for IP

* MDB must reject invalid hostnames (eg. containing '_')

In progress.

**Comment by audebert** [comment]
> ###### Originally posted 2015-04-08 14:34 by [halfr](https://bitbucket.org/halfr/) on Bitbucket

Value validation added in:

- d5a3949 mdb: validate hostname value 
- 27885b5 mdb: validate MAC address
